;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/Direct.list
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/Unbreak.list
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/China.list
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/LocalAreaNetwork.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=AE-Starzplay,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/AE-Starzplay.list
ruleset=AR-Telecom,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/AR-Telecom.list
ruleset=AU,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/AU.list
ruleset=BA-BHA,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BA-BHA.list
ruleset=BE-VOO,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BE-VOO.list
ruleset=BR-Claro,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BR-Claro.list
ruleset=BR-SkyPlus,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BR-SkyPlus.list
ruleset=BR-Watch,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BR-Watch.list
ruleset=CA-Rogers,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/CA-Rogers.list
ruleset=CA-Telus,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/CA-Telus.list
ruleset=DE,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/DE.list
ruleset=DK-Allente,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/DK-Allente.list
ruleset=DONGFANGTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/DONGFANGTV.list
ruleset=ES,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/ES.list
ruleset=FINOSW-Teliaplay,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/FINOSW-Teliaplay.list
ruleset=HK-NOWHK,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HK-NOWHK.list
ruleset=HK,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HK.list
ruleset=HR-MaxTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HR-MaxTV.list
ruleset=HU-OneTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HU-OneTV.list
ruleset=ID,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/ID.list
ruleset=IN-SonyLiv,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/IN-SonyLiv.list
ruleset=IN,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/IN.list
ruleset=IS-Stod2,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/IS-Stod2.list
ruleset=KR-LG,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/KR-LG.list
ruleset=MM,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MM.list
ruleset=MN,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MN.list
ruleset=MY-Astro,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MY-Astro.list
ruleset=MY-MANA,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MY-MANA.list
ruleset=MY-Sooka1,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MY-Sooka1.list
ruleset=MY-Sooka2,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MY-Sooka2.list
ruleset=MY-Unifi,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MY-Unifi.list
ruleset=MY,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MY.list
ruleset=NL-Delta,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/NL-Delta.list
ruleset=NP,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/NP.list
ruleset=NZ,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/NZ.list
ruleset=PH,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/PH.list
ruleset=PL-CanalPlus,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/PL-CanalPlus.list
ruleset=PL-Magenta,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/PL-Magenta.list
ruleset=PL-Polsat,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/PL-Polsat.list
ruleset=PT-Vodafone,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/PT-Vodafone.list
ruleset=RO-Vodafone,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/RO-Vodafone.list
ruleset=RU-WinkTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/RU-WinkTV.list
ruleset=SG-Singtel,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/SG-Singtel.list
ruleset=SG-Starhub,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/SG-Starhub.list
ruleset=SG,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/SG.list
ruleset=SK-DialogOpen,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/SK-DialogOpen.list
ruleset=TH-AIS,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/TH-AIS.list
ruleset=TH-TrueID,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/TH-TrueID.list
ruleset=TW-Catchplay,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/TW-Catchplay.list
ruleset=TW-FainTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/TW-Faintv.list
ruleset=TW,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/TW.list
ruleset=UK-NOWUK,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/UK-NOWUK.list
ruleset=US-Comcast,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/US-Comcast.list
ruleset=US-COX,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/US-COX.list
ruleset=US-Italkbbtv,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/US-Italkbbtv.list
ruleset=US,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/US.list
ruleset=VN,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/VN.list
ruleset=Youtube,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/Youtube.list
ruleset=Proxies,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/Proxies.list
ruleset=Proxies,[]MATCH

custom_proxy_group=Proxies`select`.*
custom_proxy_group=AR-Telecom`select`AR|阿根廷|Argentina
custom_proxy_group=AE-Starzplay`select`AE|阿联酋
custom_proxy_group=AU`select`AU|澳大利亚|澳洲|Australia|澳大利亞
custom_proxy_group=BA-BHA`select`英国|爱尔兰
custom_proxy_group=BE-VOO`select`英国|爱尔兰
custom_proxy_group=BR-Claro`select`BR|巴西|Brazil
custom_proxy_group=BR-SkyPlus`select`BR|巴西|Brazil|AR|阿根廷|Argentina|CL|智利|BO|CO|EC|GY|PE|PY|UY
custom_proxy_group=BR-Watch`select`BR|巴西|Brazil
custom_proxy_group=CA-Rogers`select`加拿大|CA|Canada
custom_proxy_group=CA-Telus`select`加拿大|CA|Canada|美国|美國
custom_proxy_group=DE`select`德国|德國|DE|Germany
custom_proxy_group=DK-Allente`select`英国|爱尔兰
custom_proxy_group=DONGFANGTV`select`台湾|TW|Taiwan|台灣
custom_proxy_group=ES`select`西班牙|Spain|espanol
custom_proxy_group=FINOSW-Teliaplay`select`挪威|瑞典|芬兰|芬蘭|FI|NO|SW
custom_proxy_group=HK-NOWHK`select`HK|香港|Hongkong
custom_proxy_group=HK`select`HK|Hong Kong|香港|hongkong|HongKong
custom_proxy_group=HR-MaxTV`select`英国|爱尔兰
custom_proxy_group=HU-OneTV`select`英国|爱尔兰
custom_proxy_group=ID`select`ID|印度尼西亚|印尼|Indonesia
custom_proxy_group=IN-SonyLiv`select`印度|IN|India
custom_proxy_group=IN`select`印度|IN|India
custom_proxy_group=IS-Stod2`select`英国|爱尔兰
custom_proxy_group=KR-LG`select`韩国|韓國|KR|Korea
custom_proxy_group=MM`select`MM|缅甸|Myanmar|Burma
custom_proxy_group=MN`select`MN|蒙古|Mongolia
custom_proxy_group=MY-Astro`select`新加坡|狮城|SG|Singapore|CT|MY|马来西亚|馬來西亞|马来
custom_proxy_group=MY-MANA`select`新加坡|马来西亚|SG|MY|Singapore|Malaysia狮城|馬來西亞|马来
custom_proxy_group=MY-Sooka1`select`新加坡|狮城|SG|Singapore|MY|马来西亚|馬來西亞|马来
custom_proxy_group=MY-Sooka2`select`新加坡|狮城|SG|Singapore|MY|马来西亚|馬來西亞|马来
custom_proxy_group=MY-Unifi`select`MY|马来西亚|馬來西亞|马来
custom_proxy_group=MY`select`马来西亚|大马|MY|Malaysia|马来
custom_proxy_group=NL-Delta`select`英国|爱尔兰
custom_proxy_group=NP`select`NP|尼泊尔|Nepal|印度|India|IN
custom_proxy_group=NZ`select`新西兰|新西蘭|紐西蘭|NZ|Newzealand|New Zealand
custom_proxy_group=PH`select`PH|菲律宾|菲律賓|Philippine
custom_proxy_group=PL-CanalPlus`select`英国|爱尔兰
custom_proxy_group=PL-Magenta`select`英国|爱尔兰
custom_proxy_group=PL-Polsat`select`英国|爱尔兰
custom_proxy_group=PT-Vodafone`select`英国|爱尔兰
custom_proxy_group=RO-Vodafone`select`英国|爱尔兰
custom_proxy_group=RU-WinkTV`select`RU|俄罗斯|俄国|俄國|俄羅斯
custom_proxy_group=SG-Singtel`select`新加坡|狮城|SG|Singapore
custom_proxy_group=SG-Starhub`select`新加坡|狮城|SG|Singapore|starhubgo|starhub
custom_proxy_group=SG`select`新加坡|狮城|SG|Singapore
custom_proxy_group=SK-DialogOpen`select`斯里兰卡|LK|Sri Lanka|SriLanka|srilanka|斯里蘭卡
custom_proxy_group=TH-AIS`select`TH|泰国|泰國|Thailand|Thai
custom_proxy_group=TH-TrueID`select`TH|泰国|泰國|Thailand|Thai
custom_proxy_group=TW-Catchplay`select`台湾|TW|Taiwan|台灣
custom_proxy_group=TW-FainTV`select`台湾|TW|Taiwan|台灣
custom_proxy_group=TW`select`台湾|台灣|新北|彰化|TW|Taiwan
custom_proxy_group=UK-NOWUK`select`UK|GB|英国|England|Great Britain|英國|United Kingdom
custom_proxy_group=US-Comcast`select`美国|美國|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|America|USA|United States
custom_proxy_group=US-COX`select`美国|美國|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|America|USA|United States
custom_proxy_group=US-Italkbbtv`select`美国|美國|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|America|USA|United States
custom_proxy_group=US`select`美国|美國|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|America|USA|United States
custom_proxy_group=VN`select`VN|越南|Vietnam|Viet
custom_proxy_group=Youtube`select`台湾|Taiwan|香港|Hongkong|美国|America|新加坡|Singapore|日本|Japan
