;设置规则标志位
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/Linux.list
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/Direct.list
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/Unbreak.list
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/China.list
ruleset=DIRECT,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/LocalAreaNetwork.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=AR-Telecom,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/AR-Telecom.list
ruleset=AU,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/AU.list
ruleset=BA-BHA,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BA-BHA.list
ruleset=BE-VOO,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BE-VOO.list
ruleset=BR-SkyPlus,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BR-SkyPlus.list
ruleset=BR-Watch,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/BR-Watch.list
ruleset=CA-Rogers,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/CA-Rogers.list
ruleset=CA-Telus,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/CA-Telus.list
ruleset=DE,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/DE.list
ruleset=DK-Allente,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/DK-Allente.list
ruleset=DONGFANGTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/DONGFANGTV.list
ruleset=ES,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/ES.list
ruleset=FINOSW-Teliaplay,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/FINOSW-Teliaplay.list
ruleset=HK-NOWHK,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HK-NOWHK.list
ruleset=HK,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HK.list
ruleset=HR-MaxTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HR-MaxTV.list
ruleset=HU-OneTV,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/HU-OneTV.list
ruleset=ID,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/ID.list
ruleset=IN-SonyLiv,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/IN-SonyLiv.list
ruleset=IN,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/IN.list
ruleset=IS-Stod2,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/IS-Stod2.list
ruleset=KR-LG,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/KR-LG.list
ruleset=MM,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MM.list
ruleset=MN,https://raw.githubusercontent.com/samkolau/Myrules/main/Rules/MN.list

custom_proxy_group=Proxies`select`.*
custom_proxy_group=AR-Telecom`select`AR|阿根廷|Argentina
custom_proxy_group=AU`select`AU|澳大利亚|澳洲|Australia|澳大利亞
custom_proxy_group=BA-BHA`select`英国|爱尔兰|丹麦|挪威|瑞典|芬兰|冰岛|爱沙尼亚|拉脱维亚|立陶宛|法国|德国|荷兰|比利时|卢森堡|奥地利|瑞士|列支敦士登|摩纳哥|俄罗斯|乌克兰|波兰|罗马尼亚|捷克|匈牙利|白俄罗斯|保加利亚|摩尔多瓦|斯洛伐克|意大利|西班牙|葡萄牙|希腊|塞尔维亚|克罗地亚|波黑|阿尔巴尼亚|斯洛文尼亚|北马其顿|黑山|马耳他|安道尔|圣马力诺|梵蒂冈
custom_proxy_group=BE-VOO`select`英国|爱尔兰|丹麦|挪威|瑞典|芬兰|冰岛|爱沙尼亚|拉脱维亚|立陶宛|法国|德国|荷兰|比利时|卢森堡|奥地利|瑞士|列支敦士登|摩纳哥|俄罗斯|乌克兰|波兰|罗马尼亚|捷克|匈牙利|白俄罗斯|保加利亚|摩尔多瓦|斯洛伐克|意大利|西班牙|葡萄牙|希腊|塞尔维亚|克罗地亚|波黑|阿尔巴尼亚|斯洛文尼亚|北马其顿|黑山|马耳他|安道尔|圣马力诺|梵蒂冈
custom_proxy_group=BR-SkyPlus`select`BR|巴西|Brazil|AR|阿根廷|Argentina|CL|智利|BO|CO|EC|GY|PE|PY|UY
custom_proxy_group=BR-Watch`select`BR|巴西|Brazil
custom_proxy_group=CA-Rogers`select`加拿大|CA|Canada
custom_proxy_group=CA-Telus`select`加拿大|CA|Canada|美国|美國|洛杉矶|硅谷|达拉斯|费利蒙|凤凰城|芝加哥|圣何塞|西雅图|US|America|USA|United States|英国|爱尔兰|丹麦|挪威|瑞典|芬兰|冰岛|爱沙尼亚|拉脱维亚|立陶宛|法国|德国|荷兰|比利时|卢森堡|奥地利|瑞士|列支敦士登|摩纳哥|俄罗斯|乌克兰|波兰|罗马尼亚|捷克|匈牙利|白俄罗斯|保加利亚|摩尔多瓦|斯洛伐克|意大利|西班牙|葡萄牙|希腊|塞尔维亚|克罗地亚|波黑|阿尔巴尼亚|斯洛文尼亚|北马其顿|黑山|马耳他|安道尔|圣马力诺|梵蒂冈|AT|BE|BG|CH|CZ|DE|DK|EE|ES|FI|FR|GB|GR|HR|HU|IS|IT|LT|LV|MC|MD|MT|NL|NO|PT|RO|RU|SE|SK|SM|UA|UK|VA|POL
custom_proxy_group=DE`select`德国|德國|DE|Germany
custom_proxy_group=DK-Allente`select`英国|爱尔兰|丹麦|挪威|瑞典|芬兰|冰岛|爱沙尼亚|拉脱维亚|立陶宛|法国|德国|荷兰|比利时|卢森堡|奥地利|瑞士|列支敦士登|摩纳哥|俄罗斯|乌克兰|波兰|罗马尼亚|捷克|匈牙利|白俄罗斯|保加利亚|摩尔多瓦|斯洛伐克|意大利|西班牙|葡萄牙|希腊|塞尔维亚|克罗地亚|波黑|阿尔巴尼亚|斯洛文尼亚|北马其顿|黑山|马耳他|安道尔|圣马力诺|梵蒂冈|AT|BE|BG|CH|CZ|DE|DK|EE|ES|FI|FR|GB|GR|HR|HU|IS|IT|LT|LV|MC|MD|MT|NL|NO|PT|RO|RU|SE|SK|SM|UA|UK|VA|POL
custom_proxy_group=DONGFANGTV`select`台湾|TW|Taiwan|台灣
custom_proxy_group=ES`select`西班牙|Spain|espanol
custom_proxy_group=FINOSW-Teliaplay`select`挪威|瑞典|芬兰|芬蘭|FI|NO|SW
custom_proxy_group=HK-NOWHK`select`HK|香港|Hongkong
custom_proxy_group=HK`select`HK|Hong Kong|香港|hongkong|HongKong
custom_proxy_group=HR-MaxTV`select`英国|爱尔兰|丹麦|挪威|瑞典|芬兰|冰岛|爱沙尼亚|拉脱维亚|立陶宛|法国|德国|荷兰|比利时|卢森堡|奥地利|瑞士|列支敦士登|摩纳哥|俄罗斯|乌克兰|波兰|罗马尼亚|捷克|匈牙利|白俄罗斯|保加利亚|摩尔多瓦|斯洛伐克|意大利|西班牙|葡萄牙|希腊|塞尔维亚|克罗地亚|波黑|阿尔巴尼亚|斯洛文尼亚|北马其顿|黑山|马耳他|安道尔|圣马力诺|梵蒂冈|AT|BE|BG|CH|CZ|DE|DK|EE|ES|FI|FR|GB|GR|HR|HU|IS|IT|LT|LV|MC|MD|MT|NL|NO|PT|RO|RU|SE|SK|SM|UA|UK|VA|POL
custom_proxy_group=HU-OneTV`select`英国|爱尔兰|丹麦|挪威|瑞典|芬兰|冰岛|爱沙尼亚|拉脱维亚|立陶宛|法国|德国|荷兰|比利时|卢森堡|奥地利|瑞士|列支敦士登|摩纳哥|俄罗斯|乌克兰|波兰|罗马尼亚|捷克|匈牙利|白俄罗斯|保加利亚|摩尔多瓦|斯洛伐克|意大利|西班牙|葡萄牙|希腊|塞尔维亚|克罗地亚|波黑|阿尔巴尼亚|斯洛文尼亚|北马其顿|黑山|马耳他|安道尔|圣马力诺|梵蒂冈|AT|BE|BG|CH|CZ|DE|DK|EE|ES|FI|FR|GB|GR|HR|HU|IS|IT|LT|LV|MC|MD|MT|NL|NO|PT|RO|RU|SE|SK|SM|UA|UK|VA|POL
custom_proxy_group=ID`select`ID|印度尼西亚|印尼|Indonesia
custom_proxy_group=IN-SonyLiv`select`印度|IN|India
custom_proxy_group=IN`select`印度|IN|India
custom_proxy_group=IS-Stod2`select`英国|爱尔兰|丹麦|挪威|瑞典|芬兰|冰岛|爱沙尼亚|拉脱维亚|立陶宛|法国|德国|荷兰|比利时|卢森堡|奥地利|瑞士|列支敦士登|摩纳哥|俄罗斯|乌克兰|波兰|罗马尼亚|捷克|匈牙利|白俄罗斯|保加利亚|摩尔多瓦|斯洛伐克|意大利|西班牙|葡萄牙|希腊|塞尔维亚|克罗地亚|波黑|阿尔巴尼亚|斯洛文尼亚|北马其顿|黑山|马耳他|安道尔|圣马力诺|梵蒂冈|AT|BE|BG|CH|CZ|DE|DK|EE|ES|FI|FR|GB|GR|HR|HU|IS|IT|LT|LV|MC|MD|MT|NL|NO|PT|RO|RU|SE|SK|SM|UA|UK|VA|POL
custom_proxy_group=KR-LG`select`韩国|韓國|KR|Korea
custom_proxy_group=MM`select`MM|缅甸|Myanmar|Burma
custom_proxy_group=MN`select`MN|蒙古|Mongolia|日本|东京|大阪|埼玉|JP|Japan|韩国|KR|Korea|HK|Hong Kong|香港|HongKong|SG|新加坡|Singapore|美国|US
